theme: hugo-fatboy

AuthorName: Bill Dueber
GitHubUser: billdueber


baseURL: http://robotlibrarian.billdueber.com
languageCode: en-us
title: Robot Librarian

permalinks:
  post: /:year/:month/:slug/

taxonomies:
  tag: tags

footnoteReturnLinkContents: "â†©"

googleAnalytics: XXXX
metaDataFormat: yaml
paginate: 10

params:
  subtitle: Bill Dueber
  twitter: billdueber
  github:  https://github.com/billdueber
  email:   bill@dueber.com

...
